import { useState } from 'react';
import styles from './style.module.css';
import Head from 'next/head';

const estagios = [
    { name: 'SOBRE' },
    { name: 'FRETE' },
    { name: 'PRODUTO' },
    { name: 'SITE' },
]

const Sobre = () => {

    const [estagio, setEstagio] = useState('SOBRE')
    const [id, setId] = useState(0)
    const [width, setWidth] = useState(120)

    return (
        <>
            <Head>
                <title>Trend Shop - Sobre</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <div className={styles.main}>
                <div className={styles.initial}>Sobre a Trend Shop</div>
                <div className={styles.aboutContent}>
                    <div className={styles.rightSide}>
                        <div className={styles.estagiosList}>
                            {estagios.map((item, index) => (
                                <>
                                    {index === id ?
                                        <div className={styles.eachEstagio} key={index} onClick={() => setEstagio(item.name)}>
                                            <div className={styles.line}
                                                style={{ background: `linear-gradient(90deg, rgba(0,0,0,0), rgb(248, 168, 20))`, width: 150 }}
                                            ></div>
                                            <div className={styles.estagio} style={{ color: `rgb(248, 168, 20)` }}>{item.name}</div>
                                        </div>
                                        :
                                        <div className={styles.eachEstagio} key={index} onClick={() => { setEstagio(item.name), setId(index) }}>
                                            <div className={styles.line}
                                                style={{ background: `linear-gradient(90deg, rgba(0,0,0,0), rgb(248, 168, 20))`, width: width }}
                                            ></div>
                                            <div className={styles.estagio}>{item.name}</div>
                                        </div>
                                    }
                                </>
                            ))}
                        </div>
                    </div>
                    <div className={styles.leftSide}>
                        <div className={styles.areaContent}>
                            {estagio === 'SOBRE' ?
                                <>
                                    <h1 className={styles.h1}>Sobre</h1>
                                    <div className={styles.line2}></div>
                                    <div className={styles.text}>
                                        Loja virtual de venda de produtos, tanto novos como usados, ficamos localizados em Rio das Pedras Jacarepagua. Nos comprometemos a trazer os mais diversos produtos sem ficar presoas à um nincho, atendemos todos os dias de 9am até as 21pm.
                                    </div>
                                    <div className={styles.space}></div>
                                </>
                                :
                                <>
                                    {estagio === 'FRETE' ?
                                        <>
                                            <h1 className={styles.h1}>Frete</h1>
                                            <div className={styles.line2}></div>
                                            <div className={styles.text}>
                                                Entregamos seus produtos em sua casa, basta clicar no botão "pedir" do produto que você será redirecionado para o whatsapp onde entrará em contato com nosso vendedor. O frete é gratuito para as regiões do Rio das Pedras, para regiões fora do Rio das Pedras será cobrada uma taxa para que o nosso entregador possa chegar. Fazemos o possivel para que a entrega seja realizada no mesmo dia do pedido feito, apenas para Regiões do Rio das Pedras.
                                            </div>
                                        </>
                                        :
                                        <>
                                            {estagio === 'PRODUTO' ?
                                                <>
                                                    <h1 className={styles.h1}>Produtos</h1>
                                                    <div className={styles.line2}></div>
                                                    <div className={styles.text}>
                                                        Trabalhamos com os mais variados tipos de produtos, a fim de atender uma demanda maior de clientes.
                                                    </div>
                                                </>
                                                :
                                                <>
                                                    {estagio === 'SITE' ?
                                                        <>
                                                            <h1 className={styles.h1}>Site</h1>
                                                            <div className={styles.line2}></div>
                                                            <div className={styles.text}>
                                                                Nosso site foi criado com um design intuitivo e de facil acesso para que todos consigam utiliza-lo, usamos outros sites como exemplo para realizar o design.
                                                            </div>
                                                        </>
                                                        :
                                                        ''
                                                    }
                                                </>
                                            }
                                        </>
                                    }
                                </>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Sobre;